### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by gilbertsoft** [GsTYPO3/core-patches#1]
This issue is meant to collect suggestions for the initial commit of this package, feel free to add your suggestions as comments.

Solved suggestions will be marked with 🎉.

**Comment by gilbertsoft** [comment]
Rename commands to `typo3:patch:apply` and `typo3:patch:remove`

**Comment by mbrodala** [comment]
Unprocessed Gerrit URLs (`https://review.typo3.org/c/Packages/TYPO3.CMS/+/<id>`) should be supported; many people will just copy them without reducing them to the change ID.

**Comment by gilbertsoft** [comment]
Detect superfluous patches during updates and suggest to remove them.

**Comment by gilbertsoft** [comment]
> Unprocessed Gerrit URLs (`https://review.typo3.org/c/Packages/TYPO3.CMS/+/<id>`) should be supported; many people will just copy them without reducing them to the change ID.

FYI other formats are already supported but not mentions in the readme see https://review.typo3.org/Documentation/rest-api-changes.html#change-id

**Comment by gilbertsoft** [comment]
Add examples for the various supported change IDs and full URLs to the readme.

**Comment by mbrodala** [comment]
Change patch file format from `<gerrit-id>-<package-slug>.patch` to `<package-slug>-review-<gerrit-id>.patch`. This makes it easier to separate patches from other manual patches for other packages.

**Comment by gilbertsoft** [comment]
Almost all requests here are handled so I'm going to close this issue now. For the pending idea a new issue was created #15 .
