### ISSUE TITLE
Do not require write permission on compose.json for `composer install`

### ISSUE THREAD

**Issue by liayn** [GsTYPO3/core-patches#59]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Ubuntu 20.04

### Composer version

2.*

### PHP version

8.2

### TYPO3 Core Patches version

Latest stable release

### Current Behavior

Whenever I checkout the project on CI and run `composer install` it fails as this composer plugin tries to write to the `composer.json` file.

> In JsonConfigSource.php line 214:
> The file "/var/www/example.com/composer.json" is not writable. 

Reading my `composer.json` I see the `applied-changes` portion, which reads like some status tracking information.
Not sure what this is about, but `composer.json` is basically a read-only _definition file_ for running `composer install`. Status information should be stored in the `vendor` folder.

### Expected Behavior

No write permissions needed for `composer.json`

### Steps To Reproduce

1. Apply any path
2. checkout the git repo with some other user
3. run `composer install`

**Comment by gilbertsoft** [comment]
Should be solved by #60

**Comment by liayn** [comment]
Does the change completely remove the modification of `composer.json`?

Generally, the `composer.json` file should never be touched by anything, except the composer-command itself.

**Comment by gilbertsoft** [comment]
> Does the change completely remove the modification of `composer.json`?
> 
> Generally, the `composer.json` file should never be touched by anything, except the composer-command itself.

My guess is you have an obsoleted core patch in your installation which is remove on `composer install` with the current version.

The patch avoids this in CI environments by default and also doesn't automatically remove patches in non interactive mode. It's also possible to deactivate this feature by a configuration.

**Comment by liayn** [comment]
The point of this issue is that `composer.json` should never be written at all!

If you need to store, which patches are applied, this should be stored in a file within the `vendor` folder.

**Comment by gilbertsoft** [comment]
> The point of this issue is that `composer.json` should never be written at all!

This plugin ofc has to change the `composer.json` to tell `cweagans/composer-patches` which patches have to be applied.

**Comment by liayn** [comment]
Okay, I never took a deeper look on how you achieve it. But I expected it to modify the config for composer-patches on the fly in memory. That explains a lot then.

I will close this issue for the time being, until I know what the exact case is at this very instance.
Thanks.

**Comment by gilbertsoft** [comment]
> Okay, I never took a deeper look on how you achieve it. But I expected it to modify the config for composer-patches on the fly in memory. That explains a lot then.
> 
> I will close this issue for the time being, until I know what the exact case is at this very instance. Thanks.

Please check if this still happens with the PR. I hardly guess it should be solved or solvable. Had at look again at the places, where `applied-changes` is modified and there are only two places of which one of them could be the issue, the removal of patches.

Sadly it's also not possible to store this information in the vendor folder or somewhere else.
